### ISSUE TITLE
Warning: Failed prop type: Invalid prop `pageSizeOptions[0]` of type `number` supplied to `Pagination`, expected `string`.

### ISSUE THREAD

**Issue by liuzhoou** [fis-components/rc-pagination#1]
Warning: Failed prop type: Invalid prop `pageSizeOptions[0]` of type `number` supplied to `Pagination`, expected `string`.

Warning: Failed prop type: Invalid prop `pageSizeOptions[0]` of type `number` supplied to `Options`, expected `string`.

**Comment by sschiessl-bcp** [comment]
I have the same error, could you please elaborate how you did resolve this?

**Comment by ramvermilion** [comment]
Issue occurs if we use numbers instead use strings instead the array

example : pageSizeOptions={[10,20,50,100]} instead of that use **pageSizeOptions={['10','20','50','100']}**
